/**
 * 
 */
var login=new Vue({
	el:"#login",
	data: {
		type:"email",
		unique:"",
		password:"",
		message:"",
		emailChosen:true,
		nameChosen:false,
	},
	methods:{
		requestLogin(){
			var info={
				"unique":this.unique,
				"password":this.password,
				"type":this.type
			}
			$.ajax({
				url:"/blog/user/loginResult",
				data:info,
				type:'POST',
				dataType:"json",
				success:function(status){
					if(status.statusCode==0){
						window.location.href="/blog/user/display/?email="
					}else{
						login.login="";
						login.password="";
						login.message=status.statusMessage;
					}
				},
				error:function(){
					alert("none");
				}
			})
		},
		emailClick(){
			this.type="email";
			this.emailChosen=true;
			this.nameChosen=false;
			this.unique="";
			this.password="";
		},
		nameClick(){
			this.type="name";
			this.emailChosen=false;
			this.nameChosen=true;
			this.unique="";
			this.password="";
		}
	}
})

